### ISSUE TITLE
Reading Delft Flexible Mesh output (_map.nc file)

### ISSUE THREAD

**Issue by JMM385** [Deltares/xugrid#14]
I'm trying to open a result map file via xu.open_dataset() but an index error raises.
More specificly:

IndexError: index 478095 is out of bounds for axis 0 with size 478095

478095 being the mesh2d_nNodes

Instead, there isn't a problem if I read the same file but through Xarray.

Same error raises if I first open the dataset via Xarray and then try to parse it to xu.UgridDataset()

I've attached my code in case it's helpful ([XUGRID.zip](https://github.com/Deltares/xugrid/files/8681095/XUGRID.zip)).
I'm new to Xugrid so any ideas would help.

Thanks in advance

**Comment by Huite** [comment]
Hi @JMM385,

This is most likely due to #11. Python has 0-based indexing, and DFM (being Fortran based) generally has 1-based indexing. This means that e.g. the face_node_connectivity has a highest value of 478095, while the array can only accept a value of 478094.

I should detect this, and automatically decrement the connectivity arrays but I haven't managed yet...

**Comment by Huite** [comment]
This should be fixed now in [9563e83](https://github.com/Deltares/xugrid/commit/9563e83eeb93346bdae4a3ef9441a4ab3c9ebb4e)

I will create a new release on PyPI and conda shortly thereafter.
