### ISSUE TITLE
Edges are not always correct

### ISSUE THREAD

**Issue by veenstrajelmer** [Deltares/xugrid#30]
I noticed some issues with uds.ugrid.sel(x,y) as was also identified in https://github.com/Deltares/xugrid/issues/26. I noticed the issues did not occur for all models and within a model not all partitions were going wrong. I also noticed that the partitions that gave issues did not have the edges drawn properly when plotting them (without using sel). I broke it down to this code, where partition 0 shows proper edges, but partition 2 has missing edges. This is clearly visible along the boundary of the partition, but I think it also happens within the domain, since some edges are drawn thicker (twice) than others (once).

```
import os
import xugrid as xu
import matplotlib.pyplot as plt
plt.close('all')

dir_testinput = r'c:\DATA\dfm_tools_testdata'
file_nc = os.path.join(dir_testinput,'DFM_3D_z_Grevelingen','computations','run01','DFM_OUTPUT_Grevelingen-FM','Grevelingen-FM_0000_map.nc')

uds1 = xu.open_dataset(file_nc.replace('_0000_','_0000_'),chunks={'time':1})
fig, ax = plt.subplots(1,1)
pc = uds1['mesh2d_flowelem_domain'].ugrid.plot(ax=ax, edgecolor='r',alpha=0.6)#,cmap='jet')
ax.set_aspect('equal')

uds2 = xu.open_dataset(file_nc.replace('_0000_','_0002_'),chunks={'time':1})
fig, ax = plt.subplots(1,1)
pc = uds2['mesh2d_flowelem_domain'].ugrid.plot(ax=ax, edgecolor='r',alpha=0.6)#,cmap='jet')
ax.set_aspect('equal')

#optional zoom in:
ax.set_xlim(50200,51300)
ax.set_ylim(420000,420900)
```

Working partitions: 0, 1, 4, 5, 6, 7
Failing partitions: 2, 3

**Comment by Huite** [comment]
A picture of the above:

![image](https://user-images.githubusercontent.com/13662783/212059614-3f1c5cec-b011-48ef-9882-f9a831a5e194.png)

Selecting the data above, then making a plot of the edge data doesn't show the issue:

```python
part = uds2.ugrid.sel(x = slice(50200,51300), y = slice(420000,420900)).max(["time", "nmesh2d_layer"])
fig, ax = plt.subplots(1,1)
pc = part['mesh2d_diu'].ugrid.plot()
ax.set_aspect('equal')
```

![image](https://user-images.githubusercontent.com/13662783/212059765-96636b9b-b31f-440f-9bca-b67b8b8a55ad.png)

So it doesn't look like e.g. the edge_node_connectivity is incorrect.

Rather it's an issue with the drawing of the polygons. It doesn't show up when no edge color is defined.
Given that it's present in only a few partitions, it's probably due to the fill_value (partition 2 and 3 have some quad faces).

**Comment by Huite** [comment]
Indeed, it's the fill_value:

```python
    nodes = grid.node_coordinates
    faces = grid.face_node_connectivity
    vertices = nodes[faces]
    # Replace fill value; PolyCollection ignores NaN.
    vertices[faces == grid.fill_value] = np.nan
```

These nan vertices are ignored by the polygon, but it also means that the edge cannot be drawn. I'll do some experimenting with `PolyCollection` to see whether there's a nice alternative.
